name:                myxmonad
version:             0.1.0.0
github:              "shanexu/.xmonad"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shanexu/.xmonad#readme>

dependencies:
- base >= 4.7 && < 5
- hostname >= 1.0 && < 2.0
- binary >= 0.8 && < 0.9
- directory >= 1.3 && < 1.4
- text >= 2.1 && < 2.2
- dbus >= 1.3 && < 1.4
- X11 >= 1.10 && < 1.11
- xmonad == 0.18.0
- xmonad-contrib == 0.18.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2

library:
  source-dirs: src

executables:
  myxmonad:
    main:                xmonad.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - myxmonad
    - xmonad
    - xmonad-contrib
    - xmonad-dbus
  xmonadctl:
    main:                xmonadctl.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - myxmonad
    - xmonad
    - xmonad-contrib
    - xmonad-dbus
